INSERT INTO Period VALUES(1,'2017-07-23');
INSERT INTO Address VALUES(1, 'Spain', 'Benicassim', 12, 41);
INSERT INTO Place VALUES(1, 'SQLand', 'LetterQ');
INSERT INTO PlacePeriod VALUES(1, 1, 1);
INSERT INTO Municipality VALUES(1);
INSERT INTO Area VALUES(1, 1, 'Area bonita', 3, 3);
INSERT INTO AreaComment VALUES(1, 1, 'SampleComment');
INSERT INTO AreaCharacteristic VALUES(1, 1, 'Pls help me');
INSERT INTO AreaImage VALUES(1, 1, 'image');
INSERT INTO AreaPeriod VALUES(1, 1, 1);
INSERT INTO Zone VALUES(1, 27);
INSERT INTO Person VALUES(1, 'Aguacate', 'Piña', 'PiñaUsername', 'password');
INSERT INTO PersonResidence VALUES(1, 1, 1);
INSERT INTO PersonEmail VALUES(1, 1, 'piña@gmail.com');
INSERT INTO PersonPhone VALUES(1, 1, '653523484');
INSERT INTO PersonPeriod VALUES(1, 1, 1);
INSERT INTO MunicipalManager VALUES(1);
INSERT INTO ControlStaff VALUES(1);
INSERT INTO Citizen VALUES(1);
INSERT INTO ServiceType VALUES(1, 1, 1);
INSERT INTO Service VALUES(1, 1, 1);
INSERT INTO ServicePeriod VALUES(1, 1, 1);
INSERT INTO Reservation VALUES(1, 1, 1, 3, 1, '2017-07-23');
INSERT INTO ReservationPeriod VALUES(1, 1, 1);
INSERT INTO ReservationZone VALUES(1, 1, 1);
INSERT INTO MunicipalManagerIsAsignedTo VALUES(1, 1, 1, 1);
INSERT INTO ControlStaffIsAssignedTo VALUES(1, 1, 1);